version: '3.8'

services:
  # Infrastructure: MongoDB Database
  mongodb:
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  # Infrastructure: Redis Streams Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Ingestion Pipeline: Log Collector Gateway
  log-collector:
    build: ./log-collector
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - LOG_STREAM=application-logs
    depends_on:
      - redis

  # Ingestion Pipeline: Log Processor Worker
  log-processor:
    build: ./log-processor
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/logcollector_db
      - LOG_STREAM=application-logs
    depends_on:
      - redis
      - mongodb

  # Backend: Analytics API
  analytics-api:
    build: ./analytics-api
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - MONGODB_URI=mongodb://mongodb:27017/logcollector_db
    depends_on:
      - mongodb

  # Microservice: Auth Service
  auth-service:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/logcollector_db
      - LOG_COLLECTOR_URL=http://log-collector:4000
      - EMAIL_SERVICE_URL=http://email-service:3002
    depends_on:
      - mongodb
      - log-collector

  # Microservice: Email Service
  email-service:
    build: ./email
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/logcollector_db
      - LOG_COLLECTOR_URL=http://log-collector:4000
    depends_on:
      - mongodb
      - log-collector

  # Microservice: Order Service
  order-service:
    build: ./orders
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/logcollector_db
      - LOG_COLLECTOR_URL=http://log-collector:4000
      - EMAIL_SERVICE_URL=http://email-service:3002
    depends_on:
      - mongodb
      - log-collector

  # Frontend: User Application
  user-app:
    build: ./Frontend/user-app
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - order-service

  # Frontend: Admin Observability Dashboard
  admin-dashboard:
    build:
      context: ./Frontend/admin-dashboard
      args:
        - NEXT_PUBLIC_ANALYTICS_API_URL=http://localhost:4002
    ports:
      - "3005:3005"
    depends_on:
      - analytics-api

volumes:
  mongo-data:
